localhost:
  path: ./src/main/java
  author: yys
server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://139.155.6.250:3306/farm?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  profiles:
    active: dev
